name: Check code detect
run-name: Check code with lint
on: [ push ]

env:
  KEYSTORE_FILE: ${{secrets.KEYSTORE_FILE}}
  KEYSTORE_REPOSITORY: ${{secrets.KEYSTORE_REPOSITORY}}
  KEYSTORE_TOKEN: ${{secrets.KEYSTORE_TOKEN}}
  KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
  RELEASE_SIGN_KEY_ALIAS: ${{secrets.RELEASE_SIGN_KEY_ALIAS}}
  RELEASE_SIGN_KEY_PASSWORD: ${{secrets.RELEASE_SIGN_KEY_PASSWORD}}
jobs:
  Build_apk:

    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true


      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_REPOSITORY}}
          token: ${{ secrets.KEYSTORE_TOKEN }}
          path: keystore


      - name: build release artifacts
        shell: bash
        run: |
          cd ..
          cd ..
          ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
          ./gradlew assembleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
  Linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true


      - name: Detekt
        shell: bash
        run: ./gradlew detekt

      - name: Publish Checkstyle Report
        # You may pin to the exact commit or the version.
        # uses: Juuxel/publish-checkstyle-report@eec483cc03443d79f49d62ccb30da6c210e322f0
        uses: Juuxel/publish-checkstyle-report@v1.0.0
        with:
          # The glob paths to all report XML files
          reports:
            '**/build/**/detekt.xml'

